export const stylesMui = {
  pageTitle: {
    textAlign: "center",
    fontFamily: "Poppins",
    fontSize: { xs: "2rem", lg: "3rem", xl: "4rem" },
    fontWeight: 600,
    lineHeight: "normal",
    textTransform: "capitalize",
  },
  subHeroText: {
    textAlign: "center",
    fontFamily: "Poppins",
    fontSize: "1.25rem",
    fontWeight: 400,
    lineHeight: "normal",
    textTransform: "capitalize",
  },
  bodyText: {
    textAlign: "center",
    fontFamily: "Montserrat",
    fontSize: "1.125rem",
    fontWeight: 500,
    lineHeight: "198.088%",
  },
  ctaButton: {
    py: { md: "0.25rem", xl: "0.75rem" },
    px: { md: "0.5rem", lg: "1.1rem", xl: "1.5rem" },
    borderRadius: "0.3125rem",
    backgroundColor: "#5B1CD4 !important",
  },
  ctaButtonText: {
    fontFamily: "Poppins",
    fontSize: "1.125rem",
    fontWeight: 500,
    lineHeight: { xs: "1rem", md: "1.8rem" },
    textTransform: "capitalize",
  },
  socialsButton: {
    px: { md: "0.5rem", lg: "1.1rem", xl: "1.5rem" },
    borderRadius: "0.3125rem",
    fontFamily: "Poppins",
    fontSize: "1.125rem",
    fontWeight: 500,
    lineHeight: "160%",
    textTransform: "capitalize",
  },
  countNumbersPrimary: {
    textAlign: "center",
    fontFamily: "Poppins",
    fontSize: "2.75rem",
    fontWeight: 600,
    lineHeight: "normal",
    textTransform: "capitalize",
  },
  pageSubheadings: {
    textAlign: "center",
    fontFamily: "Poppins",
    fontSize: { xs: "1.75rem", lg: "2rem", xl: "2.25rem" },
    fontWeight: 600,
    lineHeight: "normal",
    textTransform: "capitalize",
  },
  featureHeadings: {
    textAlign: "start",
    fontFamily: "Poppins",
    fontSize: "1.125rem",
    fontWeight: 500,
    lineHeight: "normal",
  },
  aboutHeadings: {
    fontFamily: "Poppins",
    fontSize: "1.5rem",
    fontWeight: 600,
    lineHeight: "133.2%",
    textTransform: "capitalize",
  },
  aboutCardText: {
    // color: "var(--6, #646464)",
    fontFamily: "Poppins",
    fontSize: "0.9375rem",
    fontWeight: 400,
    lineHeight: "190.5%",
  },
  testButton: {
    borderRadius: "0.25rem",
    background: "var(--4, #986AEB)",
  },
  testButtonText: {
    textAlign: "center",
    fontFamily: "Montserrat",
    fontSize: "1.625rem",
    fontWeight: 600,
    lineHeight: "1.25rem",
  },
  testTableColumnOne: {
    fontFamily: "Poppins",
    fontSize: "1.125rem",
    fontWeight: 500,
    lineHeight: "1.625rem",
  },
  testTableColumns: {
    // color: "#FFF",
    fontFamily: "Poppins",
    fontSize: "1.5rem",
    fontWeight: 400,
    lineHeight: "normal",
  },
  phaseCardHeadings: {
    fontFamily: "Mulish",
    fontSize: "1.76263rem",
    fontWeight: 700,
    lineHeight: "110%",
  },
  phaseCardText: {
    // color: "var(--6, #646464)",
    fontFamily: "Mulish",
    fontSize: "1.17506rem",
    fontWeight: 400,
    lineHeight: "150.5%",
  },
  phaseCardButton: {
    borderRadius: "1.76263rem",
    background: "rgba(255, 255, 255, 0.04) !important",
    px: "2rem",
  },
  phaseCardButtonText: {
    textAlign: "center",
    fontFamily: "Mulish",
    fontSize: "1.17506rem",
    fontWeight: 600,
    lineHeight: "145.5%",
  },
  additionalFeatureHeadings: {
    fontFamily: "Montserrat",
    fontSize: "1.5rem",
    fontWeight: 600,
    lineHeight: "110%",
  },
  additionalFeaturesText: {
    // color: "var(--6, #646464)",
    textAlign: "center",
    fontFamily: "Poppins",
    fontSize: "1.125rem",
    fontWeight: 400,
    lineHeight: "normal",
  },
  mobileAppHeading: {
    textAlign: "center",
    fontFamily: "Montserrat",
    fontSize: "4rem",
    fontWeight: 600,
    lineHeight: "normal",
    textTransform: "capitalize",
  },
  testimonialPerson: {
    fontFamily: "Poppins",
    fontSize: "1.25rem",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "110%",
  },
  testimonialText: {
    // color: "var(--6, #646464)",
    textAlign: "center",
    fontFamily: "Poppins",
    fontSize: "1.25rem",
    fontWeight: 400,
    lineHeight: "normal",
  },
  trustTitle: {
    textAlign: "center",
    fontFamily: "Montserrat",
    fontSize: "2.5rem",
    fontWeight: 600,
    lineHeight: "normal",
  },
  trustSubheading: {
    // color: "var(--5, #D6C3F8)",
    textAlign: "center",
    fontFamily: "Poppins",
    fontSize: "2rem",
    fontWeight: 600,
    lineHeight: "110%",
  },
  trustText: {
    // color: "#808080",
    fontFamily: "Poppins",
    fontSize: "1.25rem",
    fontWeight: 400,
    lineHeight: "150.5%",
  },
};
